version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "5005:5000"
    volumes:
      - .:/app
      - temp_data:/app/temp_data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1  # For better logging
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  temp_data:  # For temporary storage of PDFs and generated audio 